services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "ROOTNAME"
      MINIO_ROOT_PASSWORD: "ROOTPASS"
    volumes:
      - ~/data/orthodontist:/data
    command: server /data --console-address ":9001"

  pacs:
    image: jodogne/orthanc
    container_name: pacs
    ports:
      - "4242:4242"
      - "8042:8042"
    volumes:
      - ~/tmp/orthanc-db/:/var/lib/orthanc/db
    command:
      - /run/secrets/
    secrets:
      - orthanc.json
secrets:
  orthanc.json:
    file: orthanc.json