services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-11-07T00-52-20Z.hotfix.2e4a5c31f
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "ROOTNAME"
      MINIO_ROOT_PASSWORD: "ROOTPASS"
    volumes:
      - ~/data/orthodontist:/data
    command: server /data --console-address ":9001"

  pacs:
    image: orthancteam/orthanc:24.3.3
    container_name: pacs
    ports:
      - "4242:4242"
      - "8042:8042"
    volumes:
      - /opt/orthanc/storage:/var/lib/orthanc/db
    restart: unless-stopped
    environment:
      ORTHANC_JSON: |
        {
          "AuthenticationEnabled": false
        }

  db:
    container_name: "db"
    env_file:
      - .env-dev
    image: "postgres:17.3-alpine3.21"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - aligners_control_service:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_PASSWORD}" ]
      interval: 5s
      retries: 5
      timeout: 3s

secrets:
  orthanc.json:
    file: orthanc.json

volumes:
  aligners_control_service: