spring:
  application:
    name: control-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9090

pacs:
  address:
    base: http://localhost:8042

s3:
  uri: ${S3_URI}
  credentials:
    keyId: ${S3_KEY_ID}
    keySecret: ${S3_KEY_SECRET}
  bucket-name: ${S3_BUCKET_NAME}
