spring:
  application:
    name: control-service
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_FILE_SIZE}
      enabled: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true

server:
  port: ${APPLICATION_PORT}

pacs:
  address:
    base: ${PACS_URI}

task-poller:
  max-attempts: ${POLLER_MAX_ATTEMPTS}
  backoff: ${POLLER_BACKOFF}

s3:
  uri: ${S3_URI}
  credentials:
    keyId: ${S3_KEY_ID}
    keySecret: ${S3_KEY_SECRET}
  bucket-name: ${S3_BUCKET_NAME}

logging:
  level:
    root: info
    ru.etu.controlservice: debug
    ru.etu.grpc: info

springdoc:
  override-with-generic-response: false

grpc:
  client:
    segmentationService:
      address: ${SEGMENTATION_SERVICE_ADDRESS}
    resultPlanningService:
      address: ${RESULT_SERVICE_ADDRESS}
    treatmentPlanningService:
      address: ${TREATMENT_SERVICE_ADDRESS}