springdoc:
  swagger-ui:
    enabled: false

grpc:
  client:
    segmentationService:
      negotiation-type: tls
    resultPlanningService:
      negotiationType: tls
    treatmentPlanningService:
      negotiationType: tls
