spring:
  application:
    name: control-service
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9099

pacs:
  address:
    base: ${PACS_URI}

s3:
  uri: ${S3_URI}
  credentials:
    keyId: ${S3_KEY_ID}
    keySecret: ${S3_KEY_SECRET}
  bucket-name: ${S3_BUCKET_NAME}

grpc:
  client:
    resultPlanningService:
      address: static://localhost:9091
      negotiationType: plaintext
    treatmentPlanningService:
      address: static://localhost:9092
      negotiationType: plaintext
    segmentationService:
      address: static://localhost:9093
      negotiation-type: plaintext

