spring:
  application:
    name: control-service
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true

server:
  port: 9090

pacs:
  address:
    base: ${PACS_URI}

s3:
  uri: ${S3_URI}
  credentials:
    keyId: ${S3_KEY_ID}
    keySecret: ${S3_KEY_SECRET}
  bucket-name: ${S3_BUCKET_NAME}

